[package]
name = "fanotify-test"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.50"
fanotify-rs = {path = "/home/philip/fanotify-rs"}
memchr = "2.7.6"
nix = {version = "0.30.1", features = ["poll"]}
